steps:
# Build the Linux binary
- name: 'rtlong/gox'
  entrypoint: '/bin/sh'
  args:
  - './build.sh'

# example of how to store artifacts
artifacts:
  objects:
    location: 'gs://jess-artifacts/'
    paths:
    - 'jess-linux-amd64'
    - 'jess-darwin-amd64'
    - 'jess-darwin-arm64'
    - 'jess-windows-amd64.exe'