steps:
# Build the Linux binary
- name: 'gcr.io/cloud-builders/go'
  args:
  - '-c'
  - 'CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -ldflags="-X main.version=$(cat VERSION)" -o jess-linux-amd64'

# Build the Mac binary
- name: 'gcr.io/cloud-builders/go'
  args:
  - '-c'
  - 'CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -ldflags="-X main.version=$(cat VERSION)" -o jess-darwin-amd64'

# Build the Mac ARM64 binary
- name: 'gcr.io/cloud-builders/go'
  args:
  - '-c'
  - 'CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 go build -ldflags="-X main.version=$(cat VERSION)" -o jess-darwin-arm64'

# Build the Windows binary
- name: 'gcr.io/cloud-builders/go'
  args:
  - '-c'
  - 'CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -ldflags="-X main.version=$(cat VERSION)" -o jess-windows-amd64.exe'

# example of how to store artifacts
artifacts:
  objects:
    location: 'gs://jess-artifacts/'
    paths:
    - 'jess-linux-amd64'
    - 'jess-darwin-amd64'
    - 'jess-darwin-arm64'
    - 'jess-windows-amd64.exe'