steps:
# Run go mod tidy
- name: 'golang'
  entrypoint: '/bin/sh'
  args:
  - '-c'
  - 'go mod tidy'
  volumes:
  - name: 'gocache'
    path: '/go'

# Build the Linux binary
- name: 'rtlong/gox'
  entrypoint: '/bin/sh'
  args:
  - './build.sh'
  volumes:
  - name: 'gocache'
    path: '/go'

# example of how to store artifacts
artifacts:
  objects:
    location: 'gs://jess-artifacts/'
    paths:
    - 'jess-linux-amd64'
    - 'jess-darwin-amd64'
    - 'jess-darwin-arm64'
    - 'jess-windows-amd64.exe'
  